// Biblioteca de serviços de imigração com o checklist de documentos de cada visto.
// O escritório ativa os que atende (Configurações → Serviços) e ajusta o que quiser:
// os checklists são só o ponto de partida, editáveis documento a documento.
//
// As listas seguem a evidência inicial pedida pelo USCIS em cada formulário
// (I-130, I-485, I-140, I-129, I-765, I-751, N-400, I-589, I-914, I-918, I-360, I-131, I-821D)
// e a prática de escritório: documento do cliente, do cônjuge/dependentes e das provas do caso.
// Não substitui a análise de quem prepara o caso — é a lista de partida.
export const BIBLIOTECA_VISTOS = [
  // ---------------- Green Card por trabalho ----------------
  {
    key: 'eb2niw', nome: 'EB-2 NIW', categoria: 'Green Card por trabalho', template: 'eb2niw.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Certidão de divórcio ou óbito de casamentos anteriores',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Visto atual e status nos EUA',
      'Currículo (CV) completo',
      'Diploma de graduação (frente e verso)',
      'Diploma de pós-graduação / mestrado / doutorado',
      'Histórico escolar de todos os cursos',
      'Avaliação de equivalência do diploma (credential evaluation)',
      'Registro profissional / licença da profissão',
      'Comprovantes de experiência profissional (5 anos ou mais)',
      'Cartas de recomendação',
      'Publicações, artigos e capítulos de livro',
      'Citações do seu trabalho (Google Scholar / Scopus)',
      'Prêmios e reconhecimentos',
      'Participação como avaliador / júri / revisor',
      'Matérias na imprensa sobre você ou seu trabalho',
      'Participação em associações e entidades da área',
      'Plano profissional (proposed endeavor)',
      'Evidências de interesse do mercado americano (contratos, cartas, propostas)',
      'Comprovante de imposto de renda (últimos anos)',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'eb1a', nome: 'EB-1A (habilidade extraordinária)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Currículo (CV) completo',
      'Prêmios e reconhecimentos',
      'Participação em associações que exigem excelência',
      'Matérias na imprensa sobre você ou seu trabalho',
      'Participação como avaliador / júri / revisor',
      'Contribuições originais de destaque na área',
      'Publicações, artigos e capítulos de livro',
      'Citações do seu trabalho (Google Scholar / Scopus)',
      'Exposições, mostras ou apresentações do seu trabalho',
      'Papel de liderança em organizações de destaque',
      'Comprovantes de salário elevado (holerites, contratos, imposto de renda)',
      'Sucesso comercial nas artes (bilheteria, vendas, streams)',
      'Cartas de recomendação',
      'Plano de continuidade do trabalho nos EUA',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'eb3', nome: 'EB-3 (trabalhador qualificado)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Certidão de divórcio ou óbito de casamentos anteriores',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Oferta de emprego da empresa americana (job offer)',
      'Certificação de trabalho (PERM) aprovada',
      'Diploma de graduação (frente e verso)',
      'Histórico escolar de todos os cursos',
      'Certificados de cursos técnicos da área',
      'Comprovantes de experiência profissional',
      'Currículo (CV) completo',
      'Registro profissional / licença da profissão',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  // ---------------- Vistos de trabalho ----------------
  {
    key: 'h1b', nome: 'H-1B (trabalho especializado)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Visto atual e status nos EUA',
      'Currículo (CV) completo',
      'Diploma de graduação (frente e verso)',
      'Histórico escolar de todos os cursos',
      'Avaliação de equivalência do diploma (credential evaluation)',
      'Comprovantes de experiência profissional',
      'Oferta de emprego da empresa americana (job offer)',
      'Descrição detalhada do cargo e das funções',
      'Contrato de trabalho e tabela salarial',
      'Documentos da empresa patrocinadora (registro, faturamento, organograma)',
      'Condição de trabalho aprovada (LCA / Formulário ETA-9035)',
      'Aprovações anteriores de H-1B (I-797), se houver',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'l1', nome: 'L-1 (transferência intra-empresa)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Currículo (CV) completo',
      'Comprovante de vínculo com a empresa no exterior (1 ano nos últimos 3)',
      'Descrição do cargo no exterior e do cargo nos EUA',
      'Organograma das duas empresas',
      'Documentos societários da empresa no exterior (contrato social, alterações)',
      'Documentos da empresa americana (registro, EIN, endereço)',
      'Comprovante da relação entre as empresas (matriz, filial, afiliada)',
      'Balanços, faturamento e folha de pagamento das duas empresas',
      'Plano de negócios da operação americana (novo escritório)',
      'Contrato de locação do escritório nos EUA',
      'Holerites e imposto de renda dos últimos anos',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'o1', nome: 'O-1 (habilidade extraordinária — temporário)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Foto 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Currículo (CV) completo',
      'Prêmios e reconhecimentos',
      'Matérias na imprensa sobre você ou seu trabalho',
      'Publicações, artigos e capítulos de livro',
      'Papel de liderança em organizações de destaque',
      'Comprovantes de salário elevado (holerites, contratos, imposto de renda)',
      'Participação como avaliador / júri / revisor',
      'Cartas de recomendação',
      'Contratos de trabalho ou cartas de intenção nos EUA',
      'Itinerário das atividades nos EUA (agenda, eventos, datas)',
      'Parecer do sindicato ou entidade da área (consultation letter)',
      'Contrato com o agente ou empregador americano',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  // ---------------- Vistos temporários ----------------
  {
    key: 'f1', nome: 'F-1 (estudante)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Foto 5x5 (padrão americano)',
      'Carta de aceite da escola e Formulário I-20',
      'Comprovante de pagamento da taxa SEVIS (I-901)',
      'Formulário DS-160 preenchido e confirmação',
      'Comprovante de agendamento da entrevista no consulado',
      'Diploma e histórico escolar do último curso concluído',
      'Comprovante de proficiência em inglês (TOEFL, IELTS, Duolingo)',
      'Extratos bancários dos últimos 3 a 6 meses',
      'Comprovantes de renda do patrocinador (imposto de renda, holerites)',
      'Carta do patrocinador assumindo os custos',
      'Comprovante de vínculos com o país de origem (imóveis, emprego, família)',
      'Currículo (CV) completo',
      'Documentos do cônjuge e dos filhos (F-2), se for o caso',
    ],
  },
  {
    key: 'b1b2', nome: 'B-1/B-2 (turismo e negócios)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Foto 5x5 (padrão americano)',
      'Formulário DS-160 preenchido e confirmação',
      'Comprovante de agendamento da entrevista no consulado',
      'Comprovante de pagamento da taxa consular',
      'Comprovantes de renda (imposto de renda, holerites, pró-labore)',
      'Extratos bancários dos últimos 3 a 6 meses',
      'Comprovante de vínculo empregatício ou da empresa (contrato social)',
      'Comprovante de vínculos com o país de origem (imóveis, emprego, família)',
      'Roteiro da viagem (passagens, hospedagem, convites)',
      'Carta convite de empresa ou parente nos EUA, se houver',
      'Vistos anteriores e histórico de viagens',
      'Certidão de casamento e certidões de nascimento dos filhos',
    ],
  },
  // ---------------- Família ----------------
  {
    key: 'k1', nome: 'K-1 (noivo/noiva)', categoria: 'Família', template: 'visto-t.html',
    documentos: [
      'Passaporte do(a) beneficiário(a)',
      'Prova de cidadania americana do peticionário (passaporte, certidão ou naturalização)',
      'Certidão de nascimento dos dois',
      'Certidões de divórcio ou óbito de casamentos anteriores dos dois',
      'Fotos 5x5 dos dois',
      'Declaração de intenção de casamento dos dois (assinada)',
      'Provas de encontro presencial nos últimos 2 anos (passagens, carimbos, fotos, hospedagem)',
      'Provas do relacionamento (conversas, chamadas, viagens, presentes, declarações)',
      'Comprovante de renda do peticionário (imposto de renda, holerites, carta do empregador)',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Exame médico no consulado',
      'Formulário DS-160 preenchido e confirmação',
      'Certidões de nascimento dos filhos que vão junto (K-2)',
    ],
  },
  {
    key: 'gc_familiar', nome: 'Green Card familiar', categoria: 'Família', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Certidão de divórcio ou óbito de casamentos anteriores',
      'Fotos 5x5 do casal (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Prova do status do peticionário (passaporte americano, certidão, naturalização ou Green Card)',
      'Comprovante de endereço do peticionário nos EUA',
      'Provas de casamento de boa-fé: conta bancária conjunta',
      'Provas de casamento de boa-fé: contrato de aluguel ou escritura no nome dos dois',
      'Provas de casamento de boa-fé: contas, seguros e plano de saúde em conjunto',
      'Provas de casamento de boa-fé: fotos do casal ao longo do tempo, com família e amigos',
      'Provas de casamento de boa-fé: declarações de terceiros (affidavits)',
      'Certidões de nascimento dos filhos do casal',
      'Declaração de sustento (I-864) com imposto de renda e holerites do patrocinador',
      'Exame médico (Formulário I-693)',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Registro de mudança de nome (se houver)',
    ],
  },
  // ---------------- Humanitário ----------------
  {
    key: 'visto_t', nome: 'Visto T (vítima de tráfico)', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: [
      'Passaporte ou documento de identidade do país de origem',
      'Certidão de nascimento',
      'Fotos 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94) ou prova de entrada',
      'Declaração pessoal detalhada sobre o tráfico (personal statement)',
      'Boletim de ocorrência, registros policiais ou do FBI/ICE/HSI',
      'Declaração de cooperação com as autoridades (I-914 Supplement B), se houver',
      'Provas do tráfico: mensagens, contratos, anúncios, recibos, passagens',
      'Relatórios médicos ou psicológicos',
      'Declarações de terceiros (affidavits) que testemunharam a situação',
      'Provas de presença física nos EUA por causa do tráfico',
      'Provas de sofrimento extremo em caso de retorno ao país',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'visto_u', nome: 'Visto U (vítima de crime)', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: [
      'Passaporte ou documento de identidade do país de origem',
      'Certidão de nascimento',
      'Fotos 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94) ou prova de entrada',
      'Certificação da autoridade policial (I-918 Supplement B) assinada',
      'Declaração pessoal detalhada sobre o crime (personal statement)',
      'Boletim de ocorrência e registros policiais',
      'Documentos do processo judicial (denúncia, sentença, ordem de proteção)',
      'Relatórios médicos das lesões',
      'Relatório ou laudo psicológico',
      'Declarações de terceiros (affidavits)',
      'Provas de ajuda às autoridades na investigação',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Documentos do cônjuge e dos filhos (passaporte e certidões)',
    ],
  },
  {
    key: 'asilo', nome: 'Asilo', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Documento de identidade do país de origem (RG, carteira de identidade)',
      'Registro de entrada nos EUA (I-94) ou prova da data de entrada',
      'Declaração pessoal detalhada da perseguição (declaração escrita)',
      'Boletins de ocorrência e denúncias no país de origem',
      'Relatórios médicos das agressões ou ameaças',
      'Relatório ou laudo psicológico',
      'Ameaças recebidas: mensagens, e-mails, cartas, prints',
      'Matérias de jornal e relatórios sobre a situação do país',
      'Declarações de testemunhas (affidavits) com documento de identidade',
      'Provas de filiação a grupo político, religioso ou social',
      'Certidões de nascimento dos filhos e certidão de casamento (para incluir a família)',
      'Fotos e provas das agressões ou dos danos sofridos',
    ],
  },
  {
    key: 'vawa', nome: 'VAWA (autopetição)', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: [
      'Passaporte ou documento de identidade',
      'Certidão de nascimento',
      'Certidão de casamento com o agressor',
      'Certidão de divórcio ou óbito de casamentos anteriores',
      'Prova do status do cônjuge/parente agressor (cidadão ou residente)',
      'Fotos 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Declaração pessoal detalhada sobre o abuso',
      'Boletins de ocorrência, ordens de proteção e registros judiciais',
      'Relatórios médicos e fotos das lesões',
      'Relatório ou laudo psicológico',
      'Declarações de testemunhas, vizinhos, igreja ou profissionais (affidavits)',
      'Provas de vida em comum (contas, aluguel, fotos, correspondência)',
      'Provas de boa conduta moral (antecedentes criminais dos últimos 3 anos)',
      'Comprovante de residência atual nos EUA',
      'Certidões de nascimento dos filhos incluídos',
    ],
  },
  // ---------------- Green Card (ajuste e condições) ----------------
  {
    key: 'ajuste', nome: 'Ajuste de status (I-485)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Certidão de casamento',
      'Certidão de divórcio ou óbito de casamentos anteriores',
      'Duas fotos 5x5 (padrão americano)',
      'Documento de identidade com foto (RG, carteira de motorista)',
      'Registro de entrada nos EUA (I-94) e carimbo de entrada',
      'Visto com que entrou nos EUA',
      'Aprovação ou protocolo da petição base (I-797 do I-130, I-140 ou equivalente)',
      'Exame médico (Formulário I-693) em envelope lacrado',
      'Declaração de sustento (I-864) do patrocinador',
      'Imposto de renda, holerites e carta do empregador do patrocinador',
      'Comprovante de status legal contínuo (para categorias de trabalho)',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Registro de mudança de nome (se houver)',
      'Documentos dos dependentes que também vão ajustar',
    ],
  },
  {
    key: 'i751', nome: 'Remoção de condições (I-751)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: [
      'Green Card condicional (frente e verso)',
      'Green Card dos filhos incluídos (frente e verso)',
      'Certidão de casamento',
      'Certidões de nascimento dos filhos do casal',
      'Declarações de imposto de renda do casal (últimos 2 anos)',
      'Extratos de conta bancária conjunta',
      'Contrato de aluguel ou escritura em nome dos dois',
      'Contas de luz, água, telefone e internet em nome dos dois',
      'Apólices de seguro e plano de saúde com o cônjuge como dependente',
      'Fotos do casal ao longo do casamento, com data',
      'Viagens juntos (passagens, reservas, fotos)',
      'Declarações de terceiros sobre o casamento (affidavits)',
      'Certidão de divórcio ou anulação (se pedir dispensa)',
      'Provas de abuso ou de sofrimento extremo (se pedir dispensa)',
      'Antecedentes criminais / registros de prisão (se houver)',
    ],
  },
  // ---------------- Cidadania ----------------
  {
    key: 'n400', nome: 'Cidadania (N-400)', categoria: 'Cidadania', template: 'visto-t.html',
    documentos: [
      'Green Card (frente e verso)',
      'Passaporte e documento de identidade com foto',
      'Todos os passaportes usados no período de residência',
      'Lista de viagens para fora dos EUA (datas de saída e retorno)',
      'Certidão de casamento atual',
      'Certidões de divórcio ou óbito de casamentos anteriores',
      'Prova de cidadania do cônjuge (quando se aplica a regra de 3 anos)',
      'Declarações de imposto de renda dos últimos 3 a 5 anos',
      'Comprovantes de residência nos EUA (contas, contrato de aluguel)',
      'Comprovante de pensão alimentícia dos filhos, se houver',
      'Registro no Serviço Seletivo (homens de 18 a 26 anos)',
      'Antecedentes criminais: boletins, processos e sentenças (se houver)',
      'Registro de mudança de nome (se houver)',
      'Certidões de nascimento dos filhos',
    ],
  },
  // ---------------- Outros ----------------
  {
    key: 'daca_renov', nome: 'Renovação de DACA', categoria: 'Outros', template: 'visto-t.html',
    documentos: [
      'Aprovação anterior de DACA (I-797) e cartão de trabalho (EAD) atual',
      'Passaporte ou documento de identidade do país de origem',
      'Certidão de nascimento',
      'Duas fotos 5x5 (padrão americano)',
      'Comprovantes de residência contínua nos EUA desde a última aprovação',
      'Comprovantes de estudo ou trabalho no período',
      'Antecedentes criminais / registros de prisão (se houver)',
      'Comprovante de endereço atual',
    ],
  },
  {
    key: 'ead', nome: 'Autorização de trabalho (I-765)', categoria: 'Outros', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Certidão de nascimento',
      'Duas fotos 5x5 (padrão americano)',
      'Registro de entrada nos EUA (I-94)',
      'Cartão de trabalho anterior (EAD), se houver',
      'Protocolo ou aprovação do caso base (I-797 do I-485, asilo, U, T, VAWA…)',
      'Documento de identidade com foto',
      'Número do Social Security, se já tiver',
      'Comprovante de endereço atual',
    ],
  },
  {
    key: 'reentrada', nome: 'Permissão de reentrada / Advance Parole (I-131)', categoria: 'Outros', template: 'visto-t.html',
    documentos: [
      'Passaporte (páginas de identificação e carimbos)',
      'Green Card ou protocolo do caso em andamento (I-797)',
      'Duas fotos 5x5 (padrão americano)',
      'Documento de identidade com foto',
      'Registro de entrada nos EUA (I-94)',
      'Motivo e datas da viagem (carta explicando, com provas)',
      'Provas de vínculo com os EUA (emprego, imóvel, família, imposto de renda)',
      'Documento médico ou de emergência, em caso de viagem urgente',
      'Permissões de reentrada anteriores, se houver',
    ],
  },
];

// Orientação que aparece pro cliente no portal, por nome de documento.
// O escritório pode editar documento a documento em Configurações → Checklist por serviço.
export const DICAS_DOCUMENTOS = {
  // --- identidade e básicos ---
  'Passaporte (páginas de identificação e carimbos)': 'Foto ou digitalização da página com foto e dados e das páginas com carimbos de entrada e saída dos EUA. Precisa estar válido e legível, com os quatro cantos aparecendo.',
  'Passaporte do(a) beneficiário(a)': 'Página com foto e dados, legível e dentro da validade.',
  'Passaporte ou documento de identidade do país de origem': 'Passaporte, RG ou carteira de identidade do seu país. Se não tiver nenhum, avise que a gente vê outras formas de comprovar sua identidade.',
  'Passaporte e documento de identidade com foto': 'Passaporte e um documento americano com foto (carteira de motorista ou state ID).',
  'Todos os passaportes usados no período de residência': 'Inclua os passaportes antigos — eles mostram as viagens feitas desde que você virou residente.',
  'Documento de identidade com foto': 'Carteira de motorista, state ID ou passaporte. Frente e verso.',
  'Documento de identidade com foto (RG, carteira de motorista)': 'RG, carteira de motorista ou state ID, frente e verso, legível.',
  'Passaporte ou documento de identidade': 'Passaporte, RG ou outro documento oficial com foto. Se não tiver nenhum, avise que a gente vê outras formas de comprovar sua identidade.',
  'Documento de identidade do país de origem (RG, carteira de identidade)': 'Frente e verso, legível. Se estiver em outro idioma, cuidamos da tradução.',
  'Certidão de nascimento': 'Certidão atualizada (de preferência emitida há menos de 12 meses). Cuidamos da tradução juramentada.',
  'Certidão de nascimento dos dois': 'Certidão de nascimento sua e do(a) noivo(a), atualizadas.',
  'Certidão de casamento': 'Certidão de casamento atualizada. Se casou fora dos EUA, cuidamos da tradução.',
  'Certidão de casamento atual': 'Certidão do casamento em que você está hoje, atualizada.',
  'Certidão de casamento com o agressor': 'Certidão do casamento com a pessoa que praticou o abuso. Se não tiver a via, a gente orienta como pedir a segunda via.',
  'Certidão de divórcio ou óbito de casamentos anteriores': 'Para cada casamento anterior, seu e do seu cônjuge: certidão de divórcio (com a averbação) ou de óbito. Todas as páginas.',
  'Certidões de divórcio ou óbito de casamentos anteriores dos dois': 'Um documento para cada casamento anterior, seu e do(a) noivo(a), com todas as páginas.',
  'Certidões de divórcio ou óbito de casamentos anteriores': 'Certidão de divórcio (com averbação) ou de óbito de cada casamento anterior.',
  'Certidão de divórcio ou anulação (se pedir dispensa)': 'Decisão final do divórcio ou da anulação, com todas as páginas e o carimbo do tribunal.',
  'Registro de mudança de nome (se houver)': 'Documento oficial que mostre a troca de nome (casamento, divórcio, decisão judicial).',
  'Foto 5x5 (padrão americano)': 'Foto colorida 5x5 cm, tirada nos últimos 30 dias, fundo branco, rosto descoberto e sem óculos.',
  'Fotos 5x5 (padrão americano)': 'Fotos coloridas 5x5 cm, recentes, fundo branco, rosto descoberto e sem óculos.',
  'Duas fotos 5x5 (padrão americano)': 'Duas fotos iguais, coloridas, 5x5 cm, tiradas nos últimos 30 dias, fundo branco e sem óculos.',
  'Fotos 5x5 dos dois': 'Uma foto sua e uma do(a) noivo(a), coloridas, 5x5 cm, recentes, fundo branco.',
  'Fotos 5x5 do casal (padrão americano)': 'Uma foto sua e uma do seu cônjuge, coloridas, 5x5 cm, recentes, fundo branco.',
  'Registro de entrada nos EUA (I-94)': 'Baixe em i94.cbp.dhs.gov com seu nome, data de nascimento e número do passaporte. É a folha que mostra a data e o modo da sua entrada.',
  'Registro de entrada nos EUA (I-94) ou prova de entrada': 'O I-94 do site i94.cbp.dhs.gov. Se não aparecer, sirva-se de carimbo no passaporte, passagem aérea ou qualquer documento que mostre quando você entrou.',
  'Registro de entrada nos EUA (I-94) ou prova da data de entrada': 'O I-94 do site i94.cbp.dhs.gov, carimbo no passaporte ou passagem aérea — precisamos da data exata de entrada.',
  'Registro de entrada nos EUA (I-94) e carimbo de entrada': 'Baixe o I-94 em i94.cbp.dhs.gov e fotografe também o carimbo de entrada no passaporte.',
  'Visto atual e status nos EUA': 'Foto do visto no passaporte e do documento que mostra seu status atual (I-797, I-20, EAD…).',
  'Visto com que entrou nos EUA': 'Foto da página do visto usado na entrada. Se entrou sem visto, avise para orientarmos.',
  'Comprovante de endereço atual': 'Conta de luz, água, internet, contrato de aluguel ou correspondência oficial dos últimos 3 meses com seu nome e endereço.',
  'Comprovante de endereço nos EUA': 'Conta em seu nome, contrato de aluguel ou correspondência oficial recente.',
  'Comprovante de residência atual nos EUA': 'Conta em seu nome, contrato de aluguel ou correspondência recente com o endereço onde mora.',
  'Antecedentes criminais / registros de prisão (se houver)': 'Se você já foi preso, detido ou respondeu processo (mesmo arquivado ou de trânsito), envie boletim, denúncia e a decisão final. Não deixe de contar — o USCIS enxerga o registro de qualquer forma.',
  'Antecedentes criminais: boletins, processos e sentenças (se houver)': 'Todo registro policial ou judicial, mesmo antigo, arquivado ou sem condenação. Precisamos do documento final de cada caso.',
  'Antecedentes criminais dos últimos 3 anos': 'Certidão de antecedentes criminais dos lugares onde morou nos últimos 3 anos.',
  // --- profissional e acadêmico ---
  'Currículo (CV) completo': 'Do mais recente para o mais antigo, com datas, cargos, empresas, formação, publicações, prêmios e apresentações. Pode ser em português — nós adaptamos.',
  'Diploma de graduação (frente e verso)': 'Diploma da faculdade, frente e verso. Se for de fora dos EUA, cuidamos da tradução e da equivalência.',
  'Diploma de pós-graduação / mestrado / doutorado': 'Todos os diplomas depois da graduação, frente e verso.',
  'Diploma e histórico escolar do último curso concluído': 'Diploma e histórico do curso mais recente, com notas.',
  'Diploma / certificados': 'Diploma e certificados de cursos ligados à sua área, frente e verso.',
  'Certificados de cursos técnicos da área': 'Certificados de cursos, treinamentos e certificações profissionais, com carga horária.',
  'Histórico escolar de todos os cursos': 'Histórico completo, com disciplinas e notas, de cada curso listado.',
  'Avaliação de equivalência do diploma (credential evaluation)': 'É o laudo que compara seu diploma ao americano. Se ainda não tiver, o escritório indica o serviço — leva de 5 a 15 dias.',
  'Registro profissional / licença da profissão': 'Registro no conselho da sua profissão (CRM, CREA, OAB, COREN…) ou licença equivalente, válido.',
  'Comprovantes de experiência profissional (5 anos ou mais)': 'Carteira de trabalho, contratos, declarações em papel timbrado com cargo e período, holerites ou notas fiscais. Precisamos cobrir pelo menos 5 anos de atuação na área.',
  'Comprovantes de experiência profissional': 'Carteira de trabalho, contratos, declarações da empresa, holerites ou notas fiscais que mostrem cargo e período.',
  'Comprovante de vínculo com a empresa no exterior (1 ano nos últimos 3)': 'Carteira de trabalho, contrato, holerites ou declaração da empresa mostrando pelo menos 1 ano de trabalho contínuo nos últimos 3 anos.',
  'Comprovantes de renda (imposto de renda, holerites, pró-labore)': 'Imposto de renda dos últimos 2 anos, holerites recentes ou pró-labore. Mostram que você tem vida estabelecida no seu país.',
  'Holerites e imposto de renda dos últimos anos': 'Últimos 3 holerites e as declarações de imposto de renda dos 2 últimos anos.',
  'Comprovante de imposto de renda (últimos anos)': 'Declaração completa (não só o recibo), dos últimos 2 ou 3 anos.',
  'Comprovantes de salário elevado (holerites, contratos, imposto de renda)': 'Documentos que mostrem quanto você ganha, para comparar com a média da sua profissão. Contratos, holerites e imposto de renda servem.',
  // --- provas de mérito (EB) ---
  'Cartas de recomendação': 'Cartas de pessoas da sua área que conhecem seu trabalho (professores, clientes, chefes, parceiros). O ideal são de 4 a 6, em papel timbrado, assinadas e com o contato de quem assina. Se ainda não tiver, mande a lista de nomes que a gente te ajuda com o modelo.',
  'Publicações, artigos e capítulos de livro': 'Cada trabalho publicado, com o nome da revista/editora e a data. Se tiver link, mande junto.',
  'Citações do seu trabalho (Google Scholar / Scopus)': 'Uma captura da tela do seu perfil mostrando o número de citações e o índice h já ajuda bastante.',
  'Prêmios e reconhecimentos': 'Certificados, atas, matérias ou fotos da premiação, com data e quem concedeu. Prêmio nacional ou internacional pesa mais do que interno da empresa.',
  'Participação como avaliador / júri / revisor': 'Convites, certificados ou e-mails mostrando que você avaliou o trabalho de outros profissionais (banca, revisão de artigo, júri de prêmio, avaliação de projetos).',
  'Matérias na imprensa sobre você ou seu trabalho': 'Reportagens, entrevistas e podcasts, com nome do veículo e data. Print da página com o endereço visível serve.',
  'Participação em associações e entidades da área': 'Comprovante de filiação, principalmente em associações que exigem currículo ou indicação para aceitar membros.',
  'Participação em associações que exigem excelência': 'Comprovante de filiação e, se possível, as regras de admissão da associação (mostram que exigem destaque).',
  'Contribuições originais de destaque na área': 'Patentes, metodologias, produtos, sistemas ou pesquisas criadas por você, com provas de que outras pessoas usam ou adotaram.',
  'Exposições, mostras ou apresentações do seu trabalho': 'Catálogos, convites, programação de eventos, fotos e registros das exposições ou apresentações.',
  'Papel de liderança em organizações de destaque': 'Documento que mostre seu cargo de liderança (organograma, contrato, carta da diretoria) e a relevância da organização.',
  'Sucesso comercial nas artes (bilheteria, vendas, streams)': 'Relatórios de bilheteria, vendas, streams ou audiência, com a fonte dos números.',
  'Plano profissional (proposed endeavor)': 'Um resumo do que você pretende fazer nos EUA: área, público, onde, como e por que isso beneficia o país. Pode escrever livremente em português — nós estruturamos.',
  'Plano de continuidade do trabalho nos EUA': 'Como você vai seguir atuando na sua área nos EUA: contratos, convites, cartas de clientes, agenda de trabalhos.',
  'Evidências de interesse do mercado americano (contratos, cartas, propostas)': 'Cartas de intenção, contratos, propostas, convites ou conversas com empresas e clientes nos EUA.',
  // --- emprego e empresa ---
  'Oferta de emprego da empresa americana (job offer)': 'Carta da empresa americana com cargo, salário, local e data de início, assinada por quem pode contratar.',
  'Certificação de trabalho (PERM) aprovada': 'Cópia do PERM (ETA-9089) aprovado pelo Departamento do Trabalho.',
  'Descrição detalhada do cargo e das funções': 'O que você vai fazer no dia a dia, com requisitos de formação e experiência do cargo.',
  'Descrição do cargo no exterior e do cargo nos EUA': 'As duas descrições, mostrando que o cargo é gerencial, executivo ou de conhecimento especializado.',
  'Contrato de trabalho e tabela salarial': 'Contrato assinado e a faixa salarial do cargo na região.',
  'Documentos da empresa patrocinadora (registro, faturamento, organograma)': 'Registro da empresa, número de EIN, faturamento recente, número de funcionários e organograma.',
  'Documentos da empresa americana (registro, EIN, endereço)': 'Certificado de abertura, EIN, endereço e comprovante de atividade da empresa nos EUA.',
  'Documentos societários da empresa no exterior (contrato social, alterações)': 'Contrato social e alterações, cartão CNPJ e comprovante de atividade.',
  'Organograma das duas empresas': 'Organograma mostrando onde você está hoje e onde ficará nos EUA.',
  'Comprovante da relação entre as empresas (matriz, filial, afiliada)': 'Documentos societários que mostrem quem controla quem (participação acionária, atas).',
  'Balanços, faturamento e folha de pagamento das duas empresas': 'Balanço dos últimos 2 anos, faturamento e folha de pagamento.',
  'Plano de negócios da operação americana (novo escritório)': 'Plano com mercado, projeção de faturamento, contratações previstas e investimento.',
  'Contrato de locação do escritório nos EUA': 'Contrato assinado do espaço físico da empresa nos EUA.',
  'Condição de trabalho aprovada (LCA / Formulário ETA-9035)': 'LCA certificada pelo Departamento do Trabalho para o cargo e o local.',
  'Aprovações anteriores de H-1B (I-797), se houver': 'Todas as aprovações anteriores, para contar o tempo já usado.',
  'Contratos de trabalho ou cartas de intenção nos EUA': 'Contratos assinados ou cartas de empresas americanas dizendo o que você vai fazer e por quanto tempo.',
  'Itinerário das atividades nos EUA (agenda, eventos, datas)': 'Lista de eventos, shows, projetos ou trabalhos com datas e locais.',
  'Parecer do sindicato ou entidade da área (consultation letter)': 'Parecer da entidade da categoria sobre o seu trabalho. O escritório orienta a quem pedir.',
  'Contrato com o agente ou empregador americano': 'Contrato assinado com quem vai te representar ou contratar nos EUA.',
  // --- estudante e turista ---
  'Carta de aceite da escola e Formulário I-20': 'I-20 assinado por você e pela escola, junto com a carta de aceite.',
  'Comprovante de pagamento da taxa SEVIS (I-901)': 'Recibo do pagamento da taxa SEVIS, com o número do SEVIS ID.',
  'Formulário DS-160 preenchido e confirmação': 'Página de confirmação do DS-160 com o código de barras.',
  'Comprovante de agendamento da entrevista no consulado': 'Folha de confirmação com data, hora e local da entrevista.',
  'Comprovante de pagamento da taxa consular': 'Recibo do pagamento da taxa MRV.',
  'Comprovante de proficiência em inglês (TOEFL, IELTS, Duolingo)': 'Resultado do teste aceito pela escola, dentro da validade.',
  'Extratos bancários dos últimos 3 a 6 meses': 'Extratos completos, com nome do titular e saldo. Precisam mostrar dinheiro suficiente para o curso e a estadia.',
  'Comprovantes de renda do patrocinador (imposto de renda, holerites)': 'Imposto de renda e holerites de quem vai pagar seus custos.',
  'Carta do patrocinador assumindo os custos': 'Carta assinada dizendo quem é, qual o parentesco e que vai custear seus estudos e sua estadia.',
  'Comprovante de vínculos com o país de origem (imóveis, emprego, família)': 'Escritura de imóvel, contrato de trabalho, matrícula de filhos, contas em seu nome — mostram que você tem motivos para voltar.',
  'Comprovante de vínculo empregatício ou da empresa (contrato social)': 'Carteira de trabalho, declaração do empregador ou contrato social da sua empresa.',
  'Roteiro da viagem (passagens, hospedagem, convites)': 'Reservas, passagens e convites, mesmo que ainda não estejam pagos.',
  'Carta convite de empresa ou parente nos EUA, se houver': 'Carta com nome, endereço e status de quem convida, e o motivo da visita.',
  'Vistos anteriores e histórico de viagens': 'Fotos dos vistos antigos e dos carimbos de entrada em outros países.',
  'Certidão de casamento e certidões de nascimento dos filhos': 'Certidões atualizadas de todos que vão viajar.',
  'Documentos do cônjuge e dos filhos (F-2), se for o caso': 'Passaporte, certidão de casamento e certidões de nascimento de quem vai com você.',
  // --- família e casamento ---
  'Prova de cidadania americana do peticionário (passaporte, certidão ou naturalização)': 'Passaporte americano, certidão de nascimento nos EUA ou certificado de naturalização.',
  'Prova do status do peticionário (passaporte americano, certidão, naturalização ou Green Card)': 'Documento que comprove que quem está pedindo é cidadão ou residente permanente.',
  'Prova do status do cônjuge/parente agressor (cidadão ou residente)': 'Qualquer prova de que a pessoa é cidadã ou residente: cópia de documento, registro público, e-mail, foto do Green Card.',
  'Comprovante de endereço do peticionário nos EUA': 'Conta, contrato de aluguel ou correspondência oficial em nome de quem está pedindo.',
  'Declaração de intenção de casamento dos dois (assinada)': 'Carta simples de cada um dizendo que pretendem se casar em até 90 dias da chegada.',
  'Provas de encontro presencial nos últimos 2 anos (passagens, carimbos, fotos, hospedagem)': 'Passagens, carimbos no passaporte, reservas de hotel e fotos com data mostrando vocês juntos pessoalmente.',
  'Provas do relacionamento (conversas, chamadas, viagens, presentes, declarações)': 'Prints de conversas ao longo do tempo, registros de chamadas, fotos, comprovantes de presentes e declarações de familiares.',
  'Provas de casamento de boa-fé: conta bancária conjunta': 'Extratos de conta conjunta mostrando movimentação, de preferência desde o começo do casamento.',
  'Provas de casamento de boa-fé: contrato de aluguel ou escritura no nome dos dois': 'Contrato de aluguel, escritura ou financiamento com os dois nomes.',
  'Provas de casamento de boa-fé: contas, seguros e plano de saúde em conjunto': 'Contas de luz, água, celular, seguro de carro, plano de saúde, cartão de crédito adicional.',
  'Provas de casamento de boa-fé: fotos do casal ao longo do tempo, com família e amigos': 'Fotos de momentos diferentes (viagens, festas, família), com data. Umas 20 a 30 bem distribuídas ao longo do tempo.',
  'Provas de casamento de boa-fé: declarações de terceiros (affidavits)': 'Cartas de 2 a 4 pessoas que conhecem o casal, com nome, endereço, contato e assinatura.',
  'Certidões de nascimento dos filhos do casal': 'Certidão de cada filho em comum, atualizada.',
  'Certidões de nascimento dos filhos': 'Certidão de cada filho, atualizada.',
  'Certidões de nascimento dos filhos que vão junto (K-2)': 'Certidão de cada filho menor de 21 anos que vai com você.',
  'Certidões de nascimento dos filhos e certidão de casamento (para incluir a família)': 'Certidões de quem vai ser incluído no seu pedido.',
  'Certidões de nascimento dos filhos incluídos': 'Certidão de cada filho incluído na petição.',
  'Declaração de sustento (I-864) com imposto de renda e holerites do patrocinador': 'O patrocinador preenche o I-864 e anexa imposto de renda do último ano, W-2, holerites recentes e carta do empregador.',
  'Declaração de sustento (I-864) do patrocinador': 'Formulário assinado pelo patrocinador, com os documentos de renda dele.',
  'Imposto de renda, holerites e carta do empregador do patrocinador': 'Declaração completa do último ano, W-2, três holerites recentes e carta do empregador com cargo e salário.',
  'Comprovante de renda do peticionário (imposto de renda, holerites, carta do empregador)': 'Imposto de renda do último ano, holerites recentes e carta do empregador.',
  'Exame médico (Formulário I-693)': 'Feito por médico credenciado pelo USCIS (civil surgeon). O escritório indica um perto de você. O envelope deve chegar lacrado.',
  'Exame médico (Formulário I-693) em envelope lacrado': 'Feito por médico credenciado pelo USCIS. Não abra o envelope — precisa chegar lacrado.',
  'Exame médico no consulado': 'Feito na clínica indicada pelo consulado, no agendamento da entrevista.',
  'Aprovação ou protocolo da petição base (I-797 do I-130, I-140 ou equivalente)': 'O aviso do USCIS (I-797) da petição que dá base ao seu Green Card.',
  'Comprovante de status legal contínuo (para categorias de trabalho)': 'I-94, aprovações de visto e comprovantes que mostrem que você manteve status desde a entrada.',
  'Documentos dos dependentes que também vão ajustar': 'Passaporte, certidões e fotos de cada dependente incluído.',
  'Documentos do cônjuge e dos filhos (passaporte e certidões)': 'Passaporte, certidão de casamento e certidões de nascimento de quem vai ser incluído no processo.',
  // --- humanitário ---
  'Declaração pessoal detalhada sobre o tráfico (personal statement)': 'Conte sua história com o máximo de detalhes: como foi recrutado, o que aconteceu, datas, lugares e pessoas. Pode escrever em português, à mão ou digitado — nós organizamos e traduzimos.',
  'Declaração pessoal detalhada sobre o crime (personal statement)': 'Conte o que aconteceu com detalhes: data, local, o que sofreu, como procurou ajuda e como colaborou com a polícia. Pode escrever em português.',
  'Declaração pessoal detalhada da perseguição (declaração escrita)': 'Conte sua história completa: o que aconteceu, quem ameaçou, datas, lugares e por que você não pode voltar. Pode escrever em português — nós estruturamos e traduzimos.',
  'Declaração pessoal detalhada sobre o abuso': 'Descreva o que aconteceu, quando começou, os episódios que você lembra e o efeito na sua vida. Pode escrever em português.',
  'Declaração de cooperação com as autoridades (I-914 Supplement B), se houver': 'Formulário assinado pela autoridade que investiga o caso. Se não conseguir, existem outras formas de comprovar — a gente orienta.',
  'Certificação da autoridade policial (I-918 Supplement B) assinada': 'Formulário assinado pela polícia, promotoria ou juiz do seu caso. Vale por 6 meses depois de assinado, então avise assim que receber.',
  'Boletim de ocorrência, registros policiais ou do FBI/ICE/HSI': 'Qualquer registro feito por autoridade sobre o caso.',
  'Boletim de ocorrência e registros policiais': 'Boletim de ocorrência, relatório da polícia e número do caso.',
  'Boletins de ocorrência, ordens de proteção e registros judiciais': 'Todo documento oficial ligado ao abuso: boletim, medida protetiva, processo.',
  'Boletins de ocorrência e denúncias no país de origem': 'Registros feitos na polícia, no Ministério Público ou em órgãos de direitos humanos do seu país.',
  'Documentos do processo judicial (denúncia, sentença, ordem de proteção)': 'Peças do processo contra o autor do crime, mesmo que ainda esteja em andamento.',
  'Provas do tráfico: mensagens, contratos, anúncios, recibos, passagens': 'Prints de conversas, anúncios de emprego, contratos, recibos de pagamento, passagens — qualquer coisa que mostre como tudo aconteceu.',
  'Provas de ajuda às autoridades na investigação': 'E-mails, intimações, declarações ou registros que mostrem sua colaboração.',
  'Provas de presença física nos EUA por causa do tráfico': 'Documentos que mostrem que você está nos EUA por causa do tráfico: registros de trabalho, endereço, atendimento em abrigo.',
  'Provas de sofrimento extremo em caso de retorno ao país': 'Laudos médicos, relatórios psicológicos, provas de ameaça e relatórios sobre a situação do seu país.',
  'Relatórios médicos das lesões': 'Prontuário, atendimento de emergência, receitas e laudos.',
  'Relatórios médicos das agressões ou ameaças': 'Atendimentos, exames e laudos ligados ao que aconteceu.',
  'Relatórios médicos ou psicológicos': 'Qualquer atendimento de saúde física ou mental ligado ao caso.',
  'Relatórios médicos e fotos das lesões': 'Prontuários, laudos e fotos das lesões, com data se possível.',
  'Relatório ou laudo psicológico': 'Avaliação de psicólogo ou psiquiatra sobre o impacto do que aconteceu. Se ainda não tiver, o escritório indica um profissional.',
  'Declarações de terceiros (affidavits) que testemunharam a situação': 'Cartas de pessoas que presenciaram ou souberam dos fatos, com nome, contato e assinatura.',
  'Declarações de terceiros (affidavits)': 'Cartas de pessoas que conhecem os fatos, com nome, endereço, contato e assinatura.',
  'Declarações de testemunhas (affidavits) com documento de identidade': 'Carta assinada de cada testemunha, com cópia do documento dela.',
  'Declarações de testemunhas, vizinhos, igreja ou profissionais (affidavits)': 'Cartas de quem acompanhou a situação: vizinhos, líderes religiosos, professores, médicos, amigos.',
  'Ameaças recebidas: mensagens, e-mails, cartas, prints': 'Salve tudo: prints com data, e-mails, bilhetes, áudios. Mande do jeito que tiver.',
  'Matérias de jornal e relatórios sobre a situação do país': 'Reportagens e relatórios (ONU, Human Rights Watch, Departamento de Estado) sobre o que acontece no seu país — nós também juntamos os nossos.',
  'Provas de filiação a grupo político, religioso ou social': 'Carteirinha, declaração da entidade, fotos de eventos, publicações.',
  'Fotos e provas das agressões ou dos danos sofridos': 'Fotos de lesões, de danos ao patrimônio ou de qualquer prova visual do que aconteceu.',
  'Provas de vida em comum (contas, aluguel, fotos, correspondência)': 'Documentos que mostrem que vocês moraram juntos: contas, contrato, correspondência no mesmo endereço, fotos.',
  'Provas de boa conduta moral (antecedentes criminais dos últimos 3 anos)': 'Certidão de antecedentes das cidades onde morou nos últimos 3 anos.',
  // --- I-751, N-400, EAD, parole, DACA ---
  'Green Card condicional (frente e verso)': 'Foto dos dois lados do cartão de 2 anos.',
  'Green Card (frente e verso)': 'Foto dos dois lados do cartão, legível.',
  'Green Card dos filhos incluídos (frente e verso)': 'Foto dos dois lados do cartão de cada filho incluído.',
  'Green Card ou protocolo do caso em andamento (I-797)': 'Cartão de residente ou o aviso do USCIS do caso que está em andamento.',
  'Declarações de imposto de renda do casal (últimos 2 anos)': 'Declarações completas feitas em conjunto (ou separadas, se for o caso), com os anexos.',
  'Declarações de imposto de renda dos últimos 3 a 5 anos': 'Declarações completas — 3 anos se for pelo casamento, 5 anos nos demais casos.',
  'Extratos de conta bancária conjunta': 'Extratos com os dois nomes, mostrando uso ao longo do tempo.',
  'Contrato de aluguel ou escritura em nome dos dois': 'Contrato, escritura ou financiamento com os dois nomes e as datas.',
  'Contas de luz, água, telefone e internet em nome dos dois': 'Contas do mesmo endereço, de preferência de meses diferentes ao longo do casamento.',
  'Apólices de seguro e plano de saúde com o cônjuge como dependente': 'Seguro de carro, de vida ou plano de saúde mostrando um como dependente ou beneficiário do outro.',
  'Fotos do casal ao longo do casamento, com data': 'Fotos de momentos diferentes dos dois anos, de preferência com outras pessoas e com data.',
  'Viagens juntos (passagens, reservas, fotos)': 'Passagens, reservas de hotel e fotos das viagens do casal.',
  'Declarações de terceiros sobre o casamento (affidavits)': 'Cartas de 2 a 4 pessoas que convivem com vocês, com nome, endereço, contato e assinatura.',
  'Provas de abuso ou de sofrimento extremo (se pedir dispensa)': 'Boletins, medidas protetivas, laudos médicos e psicológicos, declarações.',
  'Lista de viagens para fora dos EUA (datas de saída e retorno)': 'Todas as viagens desde que virou residente: país, data de saída e data de volta. Use os carimbos do passaporte para conferir.',
  'Comprovantes de residência nos EUA (contas, contrato de aluguel)': 'Documentos que mostrem onde você morou nos últimos 5 anos (ou 3, se for pelo casamento).',
  'Comprovante de pensão alimentícia dos filhos, se houver': 'Comprovantes de pagamento de pensão de filhos que não moram com você.',
  'Registro no Serviço Seletivo (homens de 18 a 26 anos)': 'Comprovante em sss.gov. Se não se registrou, avise — existe como explicar.',
  'Prova de cidadania do cônjuge (quando se aplica a regra de 3 anos)': 'Passaporte americano, certidão de nascimento nos EUA ou certificado de naturalização do cônjuge.',
  'Aprovação anterior de DACA (I-797) e cartão de trabalho (EAD) atual': 'Última aprovação e o cartão de trabalho, frente e verso.',
  'Comprovantes de residência contínua nos EUA desde a última aprovação': 'Contas, contratos, registros escolares ou de trabalho que cubram todo o período.',
  'Comprovantes de estudo ou trabalho no período': 'Histórico escolar, diploma, holerites ou declaração do empregador.',
  'Cartão de trabalho anterior (EAD), se houver': 'Frente e verso do cartão, mesmo vencido.',
  'Protocolo ou aprovação do caso base (I-797 do I-485, asilo, U, T, VAWA…)': 'O aviso do USCIS do processo que dá direito ao seu cartão de trabalho.',
  'Número do Social Security, se já tiver': 'Foto do cartão ou o número. Se não tiver, dá para pedir junto com o cartão de trabalho.',
  'Motivo e datas da viagem (carta explicando, com provas)': 'Carta simples dizendo para onde vai, quando, por quanto tempo e por quê — com as provas (convite, documento médico, passagem).',
  'Provas de vínculo com os EUA (emprego, imóvel, família, imposto de renda)': 'Carta do empregador, contrato de aluguel ou escritura, imposto de renda e documentos da família.',
  'Documento médico ou de emergência, em caso de viagem urgente': 'Laudo, atestado ou documento que comprove a urgência.',
  'Permissões de reentrada anteriores, se houver': 'Documentos de Advance Parole ou reentry permit já usados.',
};
export const dicaDoDocumento = (nome) => DICAS_DOCUMENTOS[nome] || '';
