// Biblioteca de serviços de imigração com checklist de documentos pronto. O escritório ativa os que atende e ajusta.
// Formato = o mesmo que Configurações → Serviços / Checklist por serviço usam.
export const BIBLIOTECA_VISTOS = [
  { key: 'eb2niw', nome: 'EB-2 NIW', categoria: 'Green Card por trabalho', template: 'eb2niw.html',
    documentos: ['Passaporte', 'Diploma (frente e verso)', 'Histórico escolar', 'Currículo (CV)', 'Cartas de recomendação', 'Comprovantes de experiência profissional', 'Publicações / prêmios / certificados', 'Plano profissional (proposed endeavor)', 'Foto 5x5 (padrão americano)'] },
  { key: 'eb1a', nome: 'EB-1A (habilidade extraordinária)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Currículo (CV)', 'Prêmios e reconhecimentos', 'Publicações e citações', 'Cartas de recomendação', 'Comprovantes de participação em júri/banca', 'Comprovantes de salário elevado', 'Matérias na imprensa', 'Foto 5x5'] },
  { key: 'eb3', nome: 'EB-3 (trabalhador qualificado)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Oferta de emprego (job offer)', 'Diploma / certificados', 'Comprovantes de experiência', 'Currículo (CV)', 'Certidão de nascimento', 'Certidão de casamento (se houver)', 'Foto 5x5'] },
  { key: 'h1b', nome: 'H-1B (trabalho especializado)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Diploma e histórico', 'Avaliação de equivalência de diploma', 'Currículo (CV)', 'Oferta de emprego', 'Comprovantes de experiência', 'Foto 5x5'] },
  { key: 'l1', nome: 'L-1 (transferência intra-empresa)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Contrato social / documentos da empresa no Brasil', 'Documentos da empresa nos EUA', 'Organograma', 'Comprovantes de cargo e salário', 'Plano de negócios', 'Currículo (CV)', 'Foto 5x5'] },
  { key: 'o1', nome: 'O-1 (habilidade extraordinária — temporário)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Currículo (CV)', 'Portfólio / prêmios', 'Cartas de recomendação', 'Contratos ou itinerário nos EUA', 'Carta de consulta (advisory opinion)', 'Foto 5x5'] },
  { key: 'f1', nome: 'F-1 (estudante)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: ['Passaporte', 'Formulário I-20 da escola', 'Comprovante de pagamento SEVIS', 'Extratos bancários / comprovante financeiro', 'Histórico escolar', 'Carta de intenção', 'Foto 5x5'] },
  { key: 'b1b2', nome: 'B-1/B-2 (turismo e negócios)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de renda / holerites', 'Extratos bancários', 'Comprovante de vínculo empregatício', 'Comprovante de residência', 'Roteiro da viagem', 'Foto 5x5'] },
  { key: 'k1', nome: 'K-1 (noivo/noiva)', categoria: 'Família', template: 'visto-t.html',
    documentos: ['Passaporte (dos dois)', 'Comprovante de cidadania americana do(a) noivo(a)', 'Provas do relacionamento (fotos, viagens, mensagens)', 'Declaração de intenção de casamento', 'Certidões de nascimento', 'Certidões de divórcio (se houver)', 'Foto 5x5'] },
  { key: 'gc_familiar', nome: 'Green Card familiar', categoria: 'Família', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certidão de nascimento', 'Certidão de casamento', 'Comprovante de status do peticionário', 'Provas do relacionamento', 'Comprovante de renda do peticionário (I-864)', 'Exame médico', 'Foto 5x5'] },
  { key: 'visto_t', nome: 'Visto T', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de residência', 'Boletim de ocorrência', 'Declaração pessoal', 'Laudo psicológico', 'Provas da situação (mensagens, fotos, documentos)'] },
  { key: 'visto_u', nome: 'Visto U', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certificação I-918B assinada pela autoridade', 'Boletim de ocorrência', 'Declaração pessoal', 'Laudo psicológico', 'Comprovante de residência'] },
  { key: 'asilo', nome: 'Asilo', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte / documento de identidade', 'Declaração pessoal detalhada', 'Provas da perseguição (documentos, notícias, fotos)', 'Laudo psicológico', 'Certidões (nascimento, casamento)', 'Comprovante de entrada nos EUA'] },
  { key: 'vawa', nome: 'VAWA', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certidão de casamento', 'Comprovante de status do agressor', 'Provas do abuso (boletim, laudo, mensagens)', 'Declaração pessoal', 'Laudo psicológico', 'Comprovante de residência conjunta'] },
  { key: 'ajuste', nome: 'Ajuste de status (I-485)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de entrada legal (I-94)', 'Certidão de nascimento', 'Certidão de casamento (se houver)', 'Exame médico (I-693)', 'Comprovante de renda (I-864)', 'Foto 5x5'] },
  { key: 'i751', nome: 'Remoção de condições (I-751)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: ['Green Card condicional', 'Passaporte', 'Provas do casamento (contas conjuntas, fotos, contrato de aluguel)', 'Certidões de nascimento dos filhos (se houver)', 'Declarações de imposto conjuntas'] },
  { key: 'n400', nome: 'Cidadania (N-400)', categoria: 'Cidadania', template: 'visto-t.html',
    documentos: ['Green Card', 'Passaporte', 'Histórico de viagens (5 anos)', 'Declarações de imposto (5 anos)', 'Certidão de casamento (se aplicável)', 'Comprovante de residência', 'Foto 5x5'] },
  { key: 'daca_renov', nome: 'Renovação de DACA', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Documento DACA anterior', 'Passaporte / identidade', 'Comprovante de residência contínua', 'Foto 5x5'] },
  { key: 'ead', nome: 'Autorização de trabalho (I-765)', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante do status que permite o EAD', 'I-94', 'Foto 5x5'] },
  { key: 'reentrada', nome: 'Permissão de reentrada / Advance Parole', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Green Card ou comprovante de processo', 'Passaporte', 'Justificativa da viagem', 'Foto 5x5'] },
];

// Orientação que aparece pro cliente no portal, por nome de documento. O escritório pode editar
// documento a documento em Configurações → Checklist por serviço. Foco nos vistos EB, onde a
// qualidade da prova é o que decide o caso.
export const DICAS_DOCUMENTOS = {
  'Passaporte': 'Foto ou digitalização da página com foto e dados. Precisa estar válido e legível — sem reflexo e com os quatro cantos aparecendo.',
  'Diploma (frente e verso)': 'Diploma de graduação (e pós, se tiver), frente e verso. Se for de fora dos EUA, vamos providenciar a tradução juramentada e a equivalência.',
  'Diploma / certificados': 'Diploma e certificados de cursos ligados à sua área. Frente e verso, em PDF ou foto legível.',
  'Histórico escolar': 'Histórico completo do curso, com as disciplinas e notas. Se for de fora dos EUA, cuidamos da tradução.',
  'Currículo (CV)': 'Currículo completo, em ordem do mais recente para o mais antigo, com datas, cargos, empresas, formação, publicações e prêmios. Pode ser em português — nós adaptamos.',
  'Cartas de recomendação': 'Cartas de pessoas da sua área que conhecem seu trabalho (professores, clientes, chefes, parceiros). O ideal são de 4 a 6, em papel timbrado, assinadas e com o contato de quem assina. Se ainda não tiver, envie a lista de nomes que a gente te ajuda com o modelo.',
  'Comprovantes de experiência profissional': 'Carteira de trabalho, contratos, declarações da empresa, holerites ou notas fiscais que mostrem função e período. Pode enviar tudo num PDF só.',
  'Comprovantes de experiência': 'Declarações de empregadores, contratos ou registros que comprovem a função e o tempo de trabalho.',
  'Publicações / prêmios / certificados': 'Artigos, capítulos, palestras, prêmios, certificações. Envie o material e, se tiver, o link. Quantidade ajuda, mas relevância na sua área ajuda mais.',
  'Publicações e citações': 'Seus artigos publicados e as citações que eles receberam (Google Scholar, Scopus). Uma captura do perfil com o número de citações já ajuda.',
  'Prêmios e reconhecimentos': 'Certificados, atas, matérias ou fotos da premiação, com a data e quem concedeu. Prêmio nacional ou internacional pesa mais que interno da empresa.',
  'Comprovantes de participação em júri/banca': 'Convites, certificados ou e-mails mostrando que você avaliou o trabalho de outros profissionais (banca, revisão de artigo, júri de prêmio).',
  'Comprovantes de salário elevado': 'Holerites, contratos ou declaração de imposto de renda dos últimos anos, para comparar com a média da sua profissão.',
  'Matérias na imprensa': 'Reportagens, entrevistas ou publicações sobre você e seu trabalho, com o nome do veículo e a data. Print da página com o endereço visível serve.',
  'Plano profissional (proposed endeavor)': 'Um resumo do que você pretende fazer nos EUA: área, público, onde, como e por que isso beneficia o país. Pode escrever livremente em português — nós estruturamos.',
  'Foto 5x5 (padrão americano)': 'Foto colorida 5x5 cm, recente, fundo branco, rosto descoberto e sem óculos.',
  'Foto 5x5': 'Foto colorida 5x5 cm, recente, fundo branco, rosto descoberto e sem óculos.',
  'Certidão de nascimento': 'Certidão atualizada (emitida há menos de 12 meses, quando possível). Cuidamos da tradução juramentada.',
  'Certidão de casamento (se houver)': 'Certidão de casamento atualizada. Se for divorciado, envie também a averbação.',
  'Oferta de emprego (job offer)': 'Carta da empresa americana com cargo, salário, local e data de início, assinada por quem tem poder para contratar.',
};
export const dicaDoDocumento = (nome) => DICAS_DOCUMENTOS[nome] || '';
