// Biblioteca de serviços de imigração com checklist de documentos pronto. O escritório ativa os que atende e ajusta.
// Formato = o mesmo que Configurações → Serviços / Checklist por serviço usam.
export const BIBLIOTECA_VISTOS = [
  { key: 'eb2niw', nome: 'EB-2 NIW', categoria: 'Green Card por trabalho', template: 'eb2niw.html',
    documentos: ['Passaporte', 'Diploma (frente e verso)', 'Histórico escolar', 'Currículo (CV)', 'Cartas de recomendação', 'Comprovantes de experiência profissional', 'Publicações / prêmios / certificados', 'Plano profissional (proposed endeavor)', 'Foto 5x5 (padrão americano)'] },
  { key: 'eb1a', nome: 'EB-1A (habilidade extraordinária)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Currículo (CV)', 'Prêmios e reconhecimentos', 'Publicações e citações', 'Cartas de recomendação', 'Comprovantes de participação em júri/banca', 'Comprovantes de salário elevado', 'Matérias na imprensa', 'Foto 5x5'] },
  { key: 'eb3', nome: 'EB-3 (trabalhador qualificado)', categoria: 'Green Card por trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Oferta de emprego (job offer)', 'Diploma / certificados', 'Comprovantes de experiência', 'Currículo (CV)', 'Certidão de nascimento', 'Certidão de casamento (se houver)', 'Foto 5x5'] },
  { key: 'h1b', nome: 'H-1B (trabalho especializado)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Diploma e histórico', 'Avaliação de equivalência de diploma', 'Currículo (CV)', 'Oferta de emprego', 'Comprovantes de experiência', 'Foto 5x5'] },
  { key: 'l1', nome: 'L-1 (transferência intra-empresa)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Contrato social / documentos da empresa no Brasil', 'Documentos da empresa nos EUA', 'Organograma', 'Comprovantes de cargo e salário', 'Plano de negócios', 'Currículo (CV)', 'Foto 5x5'] },
  { key: 'o1', nome: 'O-1 (habilidade extraordinária — temporário)', categoria: 'Vistos de trabalho', template: 'visto-t.html',
    documentos: ['Passaporte', 'Currículo (CV)', 'Portfólio / prêmios', 'Cartas de recomendação', 'Contratos ou itinerário nos EUA', 'Carta de consulta (advisory opinion)', 'Foto 5x5'] },
  { key: 'f1', nome: 'F-1 (estudante)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: ['Passaporte', 'Formulário I-20 da escola', 'Comprovante de pagamento SEVIS', 'Extratos bancários / comprovante financeiro', 'Histórico escolar', 'Carta de intenção', 'Foto 5x5'] },
  { key: 'b1b2', nome: 'B-1/B-2 (turismo e negócios)', categoria: 'Vistos temporários', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de renda / holerites', 'Extratos bancários', 'Comprovante de vínculo empregatício', 'Comprovante de residência', 'Roteiro da viagem', 'Foto 5x5'] },
  { key: 'k1', nome: 'K-1 (noivo/noiva)', categoria: 'Família', template: 'visto-t.html',
    documentos: ['Passaporte (dos dois)', 'Comprovante de cidadania americana do(a) noivo(a)', 'Provas do relacionamento (fotos, viagens, mensagens)', 'Declaração de intenção de casamento', 'Certidões de nascimento', 'Certidões de divórcio (se houver)', 'Foto 5x5'] },
  { key: 'gc_familiar', nome: 'Green Card familiar', categoria: 'Família', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certidão de nascimento', 'Certidão de casamento', 'Comprovante de status do peticionário', 'Provas do relacionamento', 'Comprovante de renda do peticionário (I-864)', 'Exame médico', 'Foto 5x5'] },
  { key: 'visto_t', nome: 'Visto T', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de residência', 'Boletim de ocorrência', 'Declaração pessoal', 'Laudo psicológico', 'Provas da situação (mensagens, fotos, documentos)'] },
  { key: 'visto_u', nome: 'Visto U', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certificação I-918B assinada pela autoridade', 'Boletim de ocorrência', 'Declaração pessoal', 'Laudo psicológico', 'Comprovante de residência'] },
  { key: 'asilo', nome: 'Asilo', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte / documento de identidade', 'Declaração pessoal detalhada', 'Provas da perseguição (documentos, notícias, fotos)', 'Laudo psicológico', 'Certidões (nascimento, casamento)', 'Comprovante de entrada nos EUA'] },
  { key: 'vawa', nome: 'VAWA', categoria: 'Humanitário', template: 'visto-t.html',
    documentos: ['Passaporte', 'Certidão de casamento', 'Comprovante de status do agressor', 'Provas do abuso (boletim, laudo, mensagens)', 'Declaração pessoal', 'Laudo psicológico', 'Comprovante de residência conjunta'] },
  { key: 'ajuste', nome: 'Ajuste de status (I-485)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante de entrada legal (I-94)', 'Certidão de nascimento', 'Certidão de casamento (se houver)', 'Exame médico (I-693)', 'Comprovante de renda (I-864)', 'Foto 5x5'] },
  { key: 'i751', nome: 'Remoção de condições (I-751)', categoria: 'Green Card', template: 'visto-t.html',
    documentos: ['Green Card condicional', 'Passaporte', 'Provas do casamento (contas conjuntas, fotos, contrato de aluguel)', 'Certidões de nascimento dos filhos (se houver)', 'Declarações de imposto conjuntas'] },
  { key: 'n400', nome: 'Cidadania (N-400)', categoria: 'Cidadania', template: 'visto-t.html',
    documentos: ['Green Card', 'Passaporte', 'Histórico de viagens (5 anos)', 'Declarações de imposto (5 anos)', 'Certidão de casamento (se aplicável)', 'Comprovante de residência', 'Foto 5x5'] },
  { key: 'daca_renov', nome: 'Renovação de DACA', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Documento DACA anterior', 'Passaporte / identidade', 'Comprovante de residência contínua', 'Foto 5x5'] },
  { key: 'ead', nome: 'Autorização de trabalho (I-765)', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Passaporte', 'Comprovante do status que permite o EAD', 'I-94', 'Foto 5x5'] },
  { key: 'reentrada', nome: 'Permissão de reentrada / Advance Parole', categoria: 'Outros', template: 'visto-t.html',
    documentos: ['Green Card ou comprovante de processo', 'Passaporte', 'Justificativa da viagem', 'Foto 5x5'] },
];
